# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
course:
  baseurl: /128b
  number: CHEM 128B
  name: Organic Chemistry 2
  description: Upper-division course in organic chemistry for science majors.
  term: Spring 2020
  instructor:
    name: Dr. Hubert Muchalski
    office: Science I 352
    office_hours:
    email: hmuchalski@mail.fresnostate.edu
    phone: (559) 278-2711
    web: http://muchalski.net/
    # No @ before your username; e.g., twitter, not @twitter
    twitter: hubertmuchalski
    github: hmuchalski

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman