# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Organic Chemistry 2 (CHEM 128B)
email: hubert_muchalski@csufresno.edu
description: > # this means to ignore newlines until "baseurl:"
  Announcements and materials for the second semester of Organic Chemistry with Dr. Hubert Muchalski at Fresno State
baseurl: # the subpath of your site, e.g. /blog change before pushing to github
url: "http://muchalski.net" # the base hostname & protocol for your site
twitter_username: hubertmuchalski

# Build settings
markdown: kramdown
