# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Organic Chemistry (CHEM 128A)
email: hubert_muchalski@csufresno.edu
description: > # this means to ignore newlines until "baseurl:"
  Announcements and materials for the Organic Chemistry course at Fresno State
baseurl: "/128b" # the subpath of your site, e.g. /blog
url: "http://muchalski.net" # the base hostname & protocol for your site
twitter_username: hubertmuchalski

# Build settings
markdown: kramdown
